Consider the function $$f(x) = \displaystyle \frac{1}{2} x^{T}Qx + q^{T}x +10$$
where $Q$ and $c$ are given by:
$$
Q = \left[
\begin{array}{cc}
    20 & 5\\
    5 & 2
\end{array}
\right]
\hbox{ and }
q = \left[
\begin{array}{c}
    -14\\
    -6
\end{array}
\right]
$$

For this problem, $\displaystyle \frac{A}{a} = 30.234$, and
so the linear convergence rate $\delta$ of
the steepest descent algorithm is bounded above by
$\delta = \left( \displaystyle \frac{A/a-1}{A/a+1} \right)^{2} = 0.8760$.

Now we established the positive definite matrix $Q$ and the vector $q$

In [1]:
import numpy as np

In [2]:
Q = np.array([[20,5],[5,2]])
print(Q)

[[20  5]
 [ 5  2]]


In [3]:
q=np.array([[-14],[-6]])
print(q)

[[-14]
 [ -6]]


Set $k=1$.

In [4]:
k=1

Given $x^{1}=(40,-100)$.

In [5]:
x=[0]
x.append(np.array([[40],[-100]]))
print("x_%d =" % (k))
print("\n",x[k])
print(x)

x_1 =

 [[  40]
 [-100]]
[0, array([[  40],
       [-100]])]


Compute $d^{1}=Qx^{1}$.

In [6]:
d=[0]
d.append(-np.dot(Q,x[k])-q)
print("d_1 = \n",d[k])
print("norm(d_1)=%f"% np.linalg.norm(d[k]))

d_1 = 
 [[-286]
 [   6]]
norm(d_1)=286.062930


Compute the step length $\alpha=\frac{d^Td}{d^tQd}$ 

In [7]:
alpha=[0]
alpha.append(np.dot(np.transpose(d[k]),d[k])/np.dot(np.transpose(d[k]),np.dot(Q,d[k])))
print("alpha_1 = \n",alpha[k])

alpha_1 = 
 [[0.05055003]]


Compute the new iteration $x^{k+1}=x^{k}+\alpha^{k} d^{k}$

In [8]:
x.append(x[k]+alpha[k]*d[k])
print("x_1 = \n",x[k+1])

x_1 = 
 [[ 25.54269251]
 [-99.69669984]]


In [9]:
MaxIteration=60
Tol=1e-4
k=1
x=[0]
d=[0]
alpha=[0]
x.append(np.array([[40],[-100]]))
print("x_%d =" % (k))
print("\n",x[k])
LeaveLoop=0
while LeaveLoop==0:
    d.append(-np.dot(Q,x[k])-q)
    alpha.append(np.dot(np.transpose(d[k]),d[k])/np.dot(np.transpose(d[k]),np.dot(Q,d[k])))
    x.append(x[k]+alpha[k]*d[k])
    print("x_%d =" % (k))
    print("\n",x[k])
    print("|d_%d|_2 =%f\n" % (k,np.linalg.norm(d[k])))
    print("alpha_%d =" % (k))
    print("\n",alpha[k])
    if k>=MaxIteration or np.linalg.norm(d[k])<Tol:
        LeaveLoop=1
    k=k+1

x_1 =

 [[  40]
 [-100]]
x_1 =

 [[  40]
 [-100]]
|d_1|_2 =286.062930

alpha_1 =

 [[0.05055003]]
x_2 =

 [[ 25.54269251]
 [-99.69669984]]
|d_2|_2 =77.697029

alpha_2 =

 [[0.45093458]]
x_3 =

 [[ 26.27755761]
 [-64.66813006]]
|d_3|_2 =188.251915

alpha_3 =

 [[0.05055003]]
x_4 =

 [[ 16.76351181]
 [-64.46853469]]
|d_4|_2 =51.130758

alpha_4 =

 [[0.45093458]]
x_5 =

 [[ 17.24711086]
 [-41.4169798 ]]
|d_5|_2 =123.884571

alpha_5 =

 [[0.05055003]]
x_6 =

 [[ 10.98612018]
 [-41.28563034]]
|d_6|_2 =33.648062

alpha_6 =

 [[0.45093458]]
x_7 =

 [[ 11.30436641]
 [-26.11589357]]
|d_7|_2 =81.525795

alpha_7 =

 [[0.05055003]]
x_8 =

 [[  7.18414193]
 [-26.02945529]]
|d_8|_2 =22.143072

alpha_8 =

 [[0.45093458]]
x_9 =

 [[  7.39357299]
 [-16.04657497]]
|d_9|_2 =53.650387

alpha_9 =

 [[0.05055003]]
x_10 =

 [[  4.68214112]
 [-15.98969179]]
|d_10|_2 =14.571884

alpha_10 =

 [[0.45093458]]
x_11 =

 [[ 4.81996323]
 [-9.42017111]]
|d_11|_2 =35.306176

alpha_11 =

 [[0.05055003]]
x_12 =

 [[ 3.03